### PR TITLE
Add tests and promisify

### PR DESCRIPTION
**Pull request by hawyar**
not necessary, just to clean up #40 #54

### CODE REVIEW

**Comment by RIAEvangelist** [comment]
holy cow 5k files changed? This may take a sec to review, I think something is likely up here, like maybe a node_modules commit or something. I'll give feedback once I figure it out.

Also, big thanks for contributing.

**Comment by RIAEvangelist** [comment]
yes, OK, it is the node_modules folder, if you can delete that folder then comit your changes and then add the ignore of node_modules into the .gitignore, I will happily review and accept your changes!

🎉  Thank you!

**Comment by hawyar** [comment]
Oh, right I see.  I had an issue with npm cache, I will clean it up for sure.

**Comment by hawyar** [comment]
node_modules is in .gitignore and removed. Thanks

**Review by RIAEvangelist — CHANGES_REQUESTED** [review]
A LOT of the changes to the README seem unimportant changes like switching single quotes to double quotes and breaking indentation rules. This goes against the consistent style of the entire repo, unfortunately. 

Please just keep the related changes to your PR but revert the rest of the document to how it was as the indentation breaks in the code blocks and quote changes are undesired.

I'll need to look at the rest of the commits more closely still.

**Comment by hawyar** [comment]
Sorry about that recently switched IDE and it caused the unnecessary styling changes. Should be easier to review

**Comment by RIAEvangelist** [comment]
I know how that happens. I had to have my team turn theirs off at work
because they had conflicting rules and we haven't had time to make a
`.eslint` file for it.

Speaking of... When I do make one, in my free time ..., I should probably
commit it in my OSS repo's first and then have my company adopt it as well
to allow linting. Spacing code and following a style takes discipline
otherwise.

I'll have another gander at the commits today. Thanks for your patience.
Building a new tech startup is TIME CONSUMING!

**Pull request closed without merging**
